spring:
  datasource:
    url: jdbc:mysql://db:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

jwt:
  secret: change-this-secret-to-a-very-long-random-string
  accessTokenValidityMs: 3600000
  refreshTokenValidityMs: 604800000

